DO $$ BEGIN
  CREATE TYPE user_role AS ENUM ('admin', 'staff');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE equipment_status AS ENUM ('Available', 'Rented', 'Maintenance');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE payment_type AS ENUM ('checkout', 'return');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role user_role NOT NULL DEFAULT 'staff'
);

CREATE TABLE IF NOT EXISTS equipment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(100) NOT NULL,
  daily_price NUMERIC(10, 2) NOT NULL DEFAULT 0,
  status equipment_status NOT NULL DEFAULT 'Available'
);

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  nic VARCHAR(20) NOT NULL UNIQUE,
  phone VARCHAR(20),
  id_image VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS rentals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id BIGINT REFERENCES equipment(id),
  customer_id BIGINT REFERENCES customers(id),
  rent_date TIMESTAMP NOT NULL,
  expected_return TIMESTAMP NOT NULL,
  actual_return TIMESTAMP,
  total_fee NUMERIC(10, 2) DEFAULT 0,
  amount_paid NUMERIC(10, 2) DEFAULT 0,
  signature TEXT
);

CREATE TABLE IF NOT EXISTS calendar_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS payment_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rental_id BIGINT NOT NULL REFERENCES rentals(id) ON DELETE CASCADE,
  amount NUMERIC(10, 2) NOT NULL,
  payment_type payment_type NOT NULL,
  paid_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO equipment (name, type, daily_price, status)
SELECT * FROM (VALUES
  ('Sony A7S III', 'Camera Body', 15000.00, 'Available'::equipment_status),
  ('Canon 24-70mm f/2.8', 'Lens', 7500.00, 'Available'::equipment_status),
  ('DJI Ronin RS3 Pro', 'Gimbal', 10000.00, 'Available'::equipment_status),
  ('RED Komodo 6K', 'Cinema Camera', 25000.00, 'Available'::equipment_status)
) AS seed(name, type, daily_price, status)
WHERE NOT EXISTS (SELECT 1 FROM equipment);